import { test, expect } from '@playwright/test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { startWorker, stopWorker } from '../../zhilume-server/tests/worker-helper';

test('Worker management is usable without Server binding and rejects scheduling authority', async ({ page, request }) => {
  const root = await mkdtemp(join(tmpdir(), 'zhilume-admin-browser-'));
  const worker = await startWorker(root);
  try {
    const token = (await readFile(join(root,'credentials/management-token'),'utf8')).trim();
    const rejected = await request.get(worker.address + '/management/api/overview', {headers:{Authorization:'Bearer '+worker.credential}});
    expect(rejected.status()).toBe(401);
    await page.goto(worker.address + '/management');
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await page.getByRole('button', {name:'浅色主题', exact:true}).click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    await page.getByLabel('部署管理凭证').fill(token);
    await page.getByRole('button',{name:'连接',exact:true}).click();
    await expect(page.getByText('服务在线',{exact:true})).toBeVisible();
    await expect(page.getByText('未绑定',{exact:true})).toBeVisible();
    await page.reload();
    await expect(page.getByText('服务在线',{exact:true})).toBeVisible();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    await page.getByRole('button', {name:'跟随系统主题', exact:true}).click();
    await page.emulateMedia({colorScheme:'dark'});
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await page.emulateMedia({colorScheme:'light'});
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    await page.screenshot({path:'test-results/worker-light.png'});
    await page.getByRole('button', {name:'深色主题', exact:true}).click();
    await page.emulateMedia({colorScheme:'light'});
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
    await page.screenshot({path:'test-results/worker-overview.png'});
    await page.setViewportSize({width:390,height:844});
    await expect(page.getByRole('button', {name:'环境',exact:true})).toBeVisible();
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({path:'test-results/worker-mobile.png'});
    await page.setViewportSize({width:1440,height:1000});
    await page.getByRole('button',{name:'环境',exact:true}).click();
    await page.getByRole('button',{name:'填入配置模板',exact:true}).click();
    await page.getByLabel('ComfyUI 服务地址',{exact:true}).fill('http://127.0.0.1:1');
    await page.getByRole('button',{name:'添加模型',exact:true}).click();
    await page.getByLabel('主模型文件',{exact:true}).fill('shared/qwen.safetensors');
    await page.getByRole('button',{name:'高级 JSON',exact:true}).click();
    await expect(page.getByLabel('部署配置 JSON')).toContainText('shared/qwen.safetensors');
    await page.getByRole('button',{name:'返回表单',exact:true}).click();
    await expect(page.getByLabel('主模型文件',{exact:true})).toHaveValue('shared/qwen.safetensors');
    await page.getByRole('button',{name:'保存配置并停用'}).click();
    await expect(page.getByText('Qwen 图片 · 保存配置',{exact:true})).toBeVisible();
    await expect(page.getByText('完成',{exact:true})).toBeVisible();
    const saved=await request.get(worker.address+'/management/api/overview',{headers:{Authorization:'Bearer '+token}});
    expect((await saved.json()).executors.find((e:any)=>e.id==='image').config.profiles[0].models.diffusion).toBe('shared/qwen.safetensors');
    await page.getByLabel('生成引擎',{exact:true}).selectOption('speech');
    await page.getByRole('button',{name:'填入配置模板',exact:true}).click();
    await page.getByLabel('Python 程序',{exact:true}).fill('/opt/voice/bin/python');
    await page.getByLabel('工作目录',{exact:true}).fill('/opt/voice/work');
    await page.getByRole('button',{name:'高级 JSON',exact:true}).click();
    await expect(page.getByLabel('部署配置 JSON')).toContainText('/opt/voice/bin/python');
    await page.getByRole('button',{name:'返回表单',exact:true}).click();
    await page.getByLabel('生成引擎',{exact:true}).selectOption('video');
    await page.getByRole('button',{name:'填入配置模板',exact:true}).click();
    await page.getByLabel('待添加模型',{exact:true}).selectOption('minimax-h3-ref2va');
    await page.getByRole('button',{name:'添加模型',exact:true}).click();
    await expect(page.getByLabel('音频 VAE文件',{exact:true})).toBeVisible();
    await expect(page.getByLabel('FFPROBE 程序',{exact:true})).toBeVisible();
    await page.getByLabel('生成引擎',{exact:true}).selectOption('speech');
    await expect(page.getByLabel('Python 程序',{exact:true})).toHaveValue('/opt/voice/bin/python');
    await page.getByLabel('生成引擎',{exact:true}).selectOption('image');
    await expect(page.getByLabel('主模型文件',{exact:true})).toHaveValue('shared/qwen.safetensors');
    await page.screenshot({path:'test-results/worker-environment-form.png',fullPage:true});
    await page.getByRole('button',{name:'执行器',exact:true}).click();
    const image = page.locator('article').filter({has:page.getByRole('heading',{name:'Qwen 图片'})});
    await image.getByRole('button',{name:'检查环境与模型'}).click();
    // Read-only service probing is asynchronous and has its own 10-second network timeout.
    await expect(image.getByText('状态：故障', {exact:false})).toBeVisible({timeout:20000});
    await expect(image.getByRole('alert')).toBeVisible();
    await expect(image.getByText('ComfyUI 服务',{exact:true})).toBeVisible();
    await expect(image.getByText('GPU 可见性',{exact:true})).toBeVisible();
    await expect(page.getByRole('heading',{name:'IndexTTS 语音',exact:true})).toBeVisible();
    await page.screenshot({path:'test-results/worker-executor-isolation.png'});
    await page.getByRole('button',{name:'诊断',exact:true}).click();
    await page.getByRole('button',{name:'生成脱敏诊断报告'}).click();
    const report=page.locator('pre').last(); await expect(report).toContainText('executors');
    expect(await report.textContent()).not.toContain(token);
    expect(await report.textContent()).not.toContain(worker.credential);
    await page.getByRole('button',{name:'环境',exact:true}).click();
    const runtime = page.getByRole('region', {name:'托管推理服务'});
    await runtime.getByLabel('托管 Python').fill(join(root, 'missing-python'));
    await runtime.getByLabel('托管 ComfyUI 目录').fill(root);
    await runtime.getByRole('button',{name:'保存服务配置',exact:true}).click();
    await expect.poll(async () => {
      const response = await request.get(worker.address+'/management/api/overview',{headers:{Authorization:'Bearer '+token}});
      return (await response.json()).runtimes?.[0]?.id;
    }).toBe('comfy-main');
    await page.getByLabel('服务部署方式',{exact:true}).selectOption('comfy-main');
    await expect(page.getByLabel('ComfyUI 服务地址',{exact:true})).toHaveCount(0);
    await page.getByRole('button',{name:'高级 JSON',exact:true}).click();
    await expect(page.getByLabel('部署配置 JSON')).toContainText('"runtimeId": "comfy-main"');
    await page.getByRole('button',{name:'返回表单',exact:true}).click();
    await runtime.getByRole('button',{name:'检查程序路径',exact:true}).click();
    await expect(page.getByText('Python 或 ComfyUI main.py 不存在；请先配置或安装已有环境',{exact:true})).toBeVisible();
    await page.screenshot({path:'test-results/worker-managed-runtime-dark.png',fullPage:true});
    await page.getByRole('button', {name:'浅色主题', exact:true}).click();
    await page.screenshot({path:'test-results/worker-managed-runtime-light.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  } finally { await stopWorker(worker.child); await rm(root,{recursive:true,force:true,maxRetries:5,retryDelay:100}); }
});
